/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITEP;

/**
 *
 * @author mohit
 */
public class Staff extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Staff() {
        initComponents();
        setExtendedState(Staff.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheekuPanel = new javax.swing.JPanel();
        DeleteStudent = new javax.swing.JButton();
        InterviewResult = new javax.swing.JButton();
        ResultUpdate = new javax.swing.JButton();
        LabelTop = new javax.swing.JLabel();
        FinalResult = new javax.swing.JButton();
        CreateClass = new javax.swing.JButton();
        SetSchedule = new javax.swing.JButton();
        LogOut = new javax.swing.JLabel();
        Cheeku = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        CheekuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DeleteStudent.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        DeleteStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user-delete.png"))); // NOI18N
        DeleteStudent.setText("Delete Student");
        DeleteStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteStudentMouseClicked(evt);
            }
        });
        CheekuPanel.add(DeleteStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 470, 400, -1));

        InterviewResult.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        InterviewResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update.png"))); // NOI18N
        InterviewResult.setText("Interview Update");
        InterviewResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InterviewResultMouseClicked(evt);
            }
        });
        CheekuPanel.add(InterviewResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 230, 400, 80));

        ResultUpdate.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        ResultUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit.png"))); // NOI18N
        ResultUpdate.setText("Result Update");
        ResultUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultUpdateMouseClicked(evt);
            }
        });
        CheekuPanel.add(ResultUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 120, 400, 80));

        LabelTop.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        LabelTop.setText("Admin");
        CheekuPanel.add(LabelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 220, 90));

        FinalResult.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        FinalResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Result.png"))); // NOI18N
        FinalResult.setText("Final Result");
        FinalResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinalResultMouseClicked(evt);
            }
        });
        CheekuPanel.add(FinalResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 350, 400, 80));

        CreateClass.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        CreateClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Class.png"))); // NOI18N
        CreateClass.setText("Create Class");
        CreateClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateClassMouseClicked(evt);
            }
        });
        CheekuPanel.add(CreateClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 590, 400, 80));

        SetSchedule.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        SetSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/calander.png"))); // NOI18N
        SetSchedule.setText("Set Schedule");
        SetSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SetScheduleMouseClicked(evt);
            }
        });
        CheekuPanel.add(SetSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 700, 400, 80));

        LogOut.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logoutfinal.png"))); // NOI18N
        LogOut.setText("LogOut");
        LogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });
        CheekuPanel.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 910, 130, -1));

        Cheeku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cheeku.jpg"))); // NOI18N
        Cheeku.setText("LogOut");
        Cheeku.setPreferredSize(new java.awt.Dimension(1920, 1080));
        CheekuPanel.add(Cheeku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, 1160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheekuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheekuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResultUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultUpdateMouseClicked
        // TODO add your handling code here:
        new ExameResultUpdate();
    }//GEN-LAST:event_ResultUpdateMouseClicked

    private void InterviewResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InterviewResultMouseClicked
        // TODO add your handling code here:
        new InterviewResultUpdate();
    }//GEN-LAST:event_InterviewResultMouseClicked

    private void DeleteStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteStudentMouseClicked
        // TODO add your handling code here:
        new Delete_Student().setVisible(true);
    }//GEN-LAST:event_DeleteStudentMouseClicked

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutMouseClicked

    private void FinalResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinalResultMouseClicked
        // TODO add your handling code here:
        new Finalist();
    }//GEN-LAST:event_FinalResultMouseClicked

    private void CreateClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateClassMouseClicked
        // TODO add your handling code here:
        new CreateClass();
    }//GEN-LAST:event_CreateClassMouseClicked

    private void SetScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetScheduleMouseClicked
        // TODO add your handling code here:
        new Set_Schedule().setVisible(true);
    }//GEN-LAST:event_SetScheduleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cheeku;
    private javax.swing.JPanel CheekuPanel;
    private javax.swing.JButton CreateClass;
    private javax.swing.JButton DeleteStudent;
    private javax.swing.JButton FinalResult;
    private javax.swing.JButton InterviewResult;
    private javax.swing.JLabel LabelTop;
    private javax.swing.JLabel LogOut;
    private javax.swing.JButton ResultUpdate;
    private javax.swing.JButton SetSchedule;
    // End of variables declaration//GEN-END:variables
}
